# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20171015_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documents.School'),
        ),
    ]
