# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.School'),
        ),
    ]
